[package]
name = "lab3"
version = "0.1.0"
authors = ["Stepan Yurtsiv <yurtsiv.stepan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petgraph = "0.5.1"

[[bin]]
name = "lab3"
path = "main.rs"
