//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asyncClient.TaskRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Task", Namespace="http://schemas.datacontract.org/2004/07/contract")]
    [System.SerializableAttribute()]
    public partial class Task : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string textField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int timesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string text {
            get {
                return this.textField;
            }
            set {
                if ((object.ReferenceEquals(this.textField, value) != true)) {
                    this.textField = value;
                    this.RaisePropertyChanged("text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int times {
            get {
                return this.timesField;
            }
            set {
                if ((this.timesField.Equals(value) != true)) {
                    this.timesField = value;
                    this.RaisePropertyChanged("times");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TaskRef.IAsyncTask", CallbackContract=typeof(asyncClient.TaskRef.IAsyncTaskCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IAsyncTask {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAsyncTask/Repeat")]
        void Repeat(asyncClient.TaskRef.Task task);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAsyncTask/Repeat")]
        System.Threading.Tasks.Task RepeatAsync(asyncClient.TaskRef.Task task);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAsyncTask/GetTaskById", ReplyAction="http://tempuri.org/IAsyncTask/GetTaskByIdResponse")]
        asyncClient.TaskRef.Task GetTaskById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAsyncTask/GetTaskById", ReplyAction="http://tempuri.org/IAsyncTask/GetTaskByIdResponse")]
        System.Threading.Tasks.Task<asyncClient.TaskRef.Task> GetTaskByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAsyncTask/AddTask", ReplyAction="http://tempuri.org/IAsyncTask/AddTaskResponse")]
        void AddTask(asyncClient.TaskRef.Task task);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAsyncTask/AddTask", ReplyAction="http://tempuri.org/IAsyncTask/AddTaskResponse")]
        System.Threading.Tasks.Task AddTaskAsync(asyncClient.TaskRef.Task task);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAsyncTask/RemoveTask", ReplyAction="http://tempuri.org/IAsyncTask/RemoveTaskResponse")]
        asyncClient.TaskRef.Task RemoveTask(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAsyncTask/RemoveTask", ReplyAction="http://tempuri.org/IAsyncTask/RemoveTaskResponse")]
        System.Threading.Tasks.Task<asyncClient.TaskRef.Task> RemoveTaskAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAsyncTask/UpdateTask", ReplyAction="http://tempuri.org/IAsyncTask/UpdateTaskResponse")]
        asyncClient.TaskRef.Task UpdateTask(int id, string text, int times);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAsyncTask/UpdateTask", ReplyAction="http://tempuri.org/IAsyncTask/UpdateTaskResponse")]
        System.Threading.Tasks.Task<asyncClient.TaskRef.Task> UpdateTaskAsync(int id, string text, int times);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAsyncTaskCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAsyncTask/RepeatResult")]
        void RepeatResult(string result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAsyncTaskChannel : asyncClient.TaskRef.IAsyncTask, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AsyncTaskClient : System.ServiceModel.DuplexClientBase<asyncClient.TaskRef.IAsyncTask>, asyncClient.TaskRef.IAsyncTask {
        
        public AsyncTaskClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public AsyncTaskClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public AsyncTaskClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public AsyncTaskClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public AsyncTaskClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Repeat(asyncClient.TaskRef.Task task) {
            base.Channel.Repeat(task);
        }
        
        public System.Threading.Tasks.Task RepeatAsync(asyncClient.TaskRef.Task task) {
            return base.Channel.RepeatAsync(task);
        }
        
        public asyncClient.TaskRef.Task GetTaskById(int id) {
            return base.Channel.GetTaskById(id);
        }
        
        public System.Threading.Tasks.Task<asyncClient.TaskRef.Task> GetTaskByIdAsync(int id) {
            return base.Channel.GetTaskByIdAsync(id);
        }
        
        public void AddTask(asyncClient.TaskRef.Task task) {
            base.Channel.AddTask(task);
        }
        
        public System.Threading.Tasks.Task AddTaskAsync(asyncClient.TaskRef.Task task) {
            return base.Channel.AddTaskAsync(task);
        }
        
        public asyncClient.TaskRef.Task RemoveTask(int id) {
            return base.Channel.RemoveTask(id);
        }
        
        public System.Threading.Tasks.Task<asyncClient.TaskRef.Task> RemoveTaskAsync(int id) {
            return base.Channel.RemoveTaskAsync(id);
        }
        
        public asyncClient.TaskRef.Task UpdateTask(int id, string text, int times) {
            return base.Channel.UpdateTask(id, text, times);
        }
        
        public System.Threading.Tasks.Task<asyncClient.TaskRef.Task> UpdateTaskAsync(int id, string text, int times) {
            return base.Channel.UpdateTaskAsync(id, text, times);
        }
    }
}
