#ifndef CONSTANTS_H
#define CONSTANTS_H

#define DEF_MAT_HEIGHT 5
#define DEF_MAT_WIDTH 4

#define DEF_TAB_WIDTH 4

#define DEF_MSCN_RAND_C_MIN 2
#define DEF_MSCN_RAND_C_MAX 20
#define DEF_MSCN_RAND_S_MIN 1
#define DEF_MSCN_RAND_S_MAX 1000
#define DEF_MSCN_RAND_U_MIN 1
#define DEF_MSCN_RAND_U_MAX 3
#define DEF_MSCN_RAND_P_MIN 60
#define DEF_MSCN_RAND_P_MAX 500

#define DEF_MSCN_D 2
#define DEF_MSCN_F 2
#define DEF_MSCN_M 2
#define DEF_MSCN_S 3

#define DEF_RANDOM_SEARCH_MAX_ITER 3
#define DEF_DIFF_EVOL_POP_NUMBER 500
#define DEF_DIFF_EVOL_CROSS_PROB 0.7
#define DEF_DIFF_EVOL_DIFF_WEIGHT 0.4
#define DEF_DIFF_EVOL_ITER_TIME 5

#define E_OK 0
#define E_NULLPTR 1
#define E_INV_ARR_SIZE 2
#define E_BAD_ARR_VAL 3

#endif // CONSTANTS_H
